---
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - Gemfile
  - Rakefile
  - 'test/**/*'
  - 'examples/**/*'
  - 'vendor/**/*'
  - 'lib/bundles/inspec-init/templates/**/*'
  - 'www/tutorial/**/*'
AlignParameters:
  Enabled: true
BlockDelimiters:
  Enabled: false
Documentation:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf
Layout/SpaceAroundOperators:
  Enabled: false
MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 33
Metrics/BlockLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 11
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/PredicateName:
  Enabled: false
NumericLiterals:
  MinDigits: 10
Security/YAMLLoad:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/UnlessElse:
  Enabled: false
